# Generated by Django 4.2.16 on 2024-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('copy', models.TextField()),
            ],
        ),
    ]
